# Simple MLP Training (Direct Dataset Files)

This notebook is basic and direct.

It uses these files as datasets:
- `/data/top_dataset.csv`
- `/data/bottom_dataset.csv`

Classical evaluation settings are kept:
- `RobustScaler`
- `StratifiedKFold(n_splits=10, shuffle=True, random_state=90483257)`
- `cross_val_predict`
- metrics: `accuracy`, `macro_f1`, `balanced_accuracy`

In [1]:
from pathlib import Path
import pandas as pd

from sklearn.neural_network import MLPClassifier
from sklearn.pipeline import make_pipeline
from sklearn.preprocessing import RobustScaler
from sklearn.model_selection import StratifiedKFold, cross_val_predict
from sklearn.metrics import accuracy_score, f1_score, balanced_accuracy_score

In [4]:
TOP_FILE = "../data/top_dataset.csv"
BOTTOM_FILE = "../data/bottom_dataset.csv"

## Top File: Load CSV, then Train on ALL Listed Datasets

In [12]:
top_df = pd.read_csv(TOP_FILE)

print("Top CSV length:", len(top_df))
display(top_df.head(10))

print("\nLoading and preparing all top datasets...")

Top CSV length: 54

,dataset,target_column,rows,features,classes,class_imbalance,missing_values_count,missing_values_ratio,numeric_features,categorical_features,feature_type
0,agaricus_lepiota.tsv.gz,target,8145,22,2,0.000729,0,0,22,0,numeric
1,allbp.tsv.gz,target,3772,29,3,0.583682,0,0,29,0,numeric
2,allhyper.tsv.gz,target,3771,29,4,0.697607,0,0,29,0,numeric
3,allhypo.tsv.gz,target,3770,29,3,0.522510,0,0,29,0,numeric
4,allrep.tsv.gz,target,3772,29,4,0.685706,0,0,29,0,numeric
5,analcatdata_authorship.tsv.gz,target,841,70,4,0.062548,0,0,70,0,numeric
6,analcatdata_bankruptcy.tsv.gz,target,50,6,2,0.000000,0,0,6,0,numeric
7,analcatdata_creditscore.tsv.gz,target,100,6,2,0.105800,0,0,6,0,numeric
8,analcatdata_cyyoung9302.tsv.gz,target,92,10,2,0.172259,0,0,10,0,numeric
9,analcatdata_lawsuit.tsv.gz,target,264,4,2,0.366420,0,0,4,0,numeric

Loading and preparing all top datasets...

## Top Dataset: Explicit MLP Code

In [13]:
# MLP training loop for all top datasets
top_results = []

for idx, row in top_df.iterrows():
    dataset_name = row["dataset"]
    dataset_path = f"../data/{dataset_name}"
    
    try:
        # Load dataset
        data = pd.read_csv(dataset_path, compression="gzip", sep="\t")
        label_col = "class" if "class" in data.columns else "target"
        
        X = data.drop(columns=[label_col]).values.astype(float)
        y = data[label_col].values
        
        # MLP training
        mlp = MLPClassifier(
            hidden_layer_sizes=(100,),
            activation="relu",
            solver="adam",
            max_iter=1000,
            early_stopping=True,
            random_state=324089
        )
        
        pipeline = make_pipeline(RobustScaler(), mlp)
        cv = StratifiedKFold(n_splits=10, shuffle=True, random_state=90483257)
        pred = cross_val_predict(pipeline, X, y, cv=cv)
        
        # Metrics
        accuracy = accuracy_score(y, pred)
        macro_f1 = f1_score(y, pred, average="macro", zero_division=0)
        balanced_accuracy = balanced_accuracy_score(y, pred)
        
        top_results.append({
            "dataset": dataset_name,
            "accuracy": accuracy,
            "macro_f1": macro_f1,
            "balanced_accuracy": balanced_accuracy,
        })
        
        print(f"[{idx+1}/{len(top_df)}] {dataset_name}: BA={balanced_accuracy:.4f}")
    except Exception as e:
        print(f"[{idx+1}/{len(top_df)}] {dataset_name}: ERROR - {e}")

top_results_df = pd.DataFrame(top_results)
print(f"\nTop Results ({len(top_results_df)} datasets):")
display(top_results_df)

[1/54] agaricus_lepiota.tsv.gz: BA=0.9985
[2/54] allbp.tsv.gz: BA=0.4172
[3/54] allhyper.tsv.gz: BA=0.2499
[4/54] allhypo.tsv.gz: BA=0.4173
[5/54] allrep.tsv.gz: BA=0.2500
[6/54] analcatdata_authorship.tsv.gz: BA=0.9851
[7/54] analcatdata_bankruptcy.tsv.gz: BA=0.6200
[8/54] analcatdata_creditscore.tsv.gz: BA=0.4452
[9/54] analcatdata_cyyoung9302.tsv.gz: BA=0.4715
[10/54] analcatdata_lawsuit.tsv.gz: BA=0.5241
[11/54] ann_thyroid.tsv.gz: BA=0.8780
[12/54] appendicitis.tsv.gz: BA=0.6793
[13/54] backache.tsv.gz: BA=0.4710
[14/54] breast_cancer.tsv.gz: BA=0.5975
[15/54] chess.tsv.gz: BA=0.9808
[16/54] churn.tsv.gz: BA=0.7359
[17/54] clean1.tsv.gz: BA=0.7906
[18/54] clean2.tsv.gz: BA=0.9925
[19/54] coil2000.tsv.gz: BA=0.5005
[20/54] collins.tsv.gz: BA=0.3983
[21/54] confidence.tsv.gz: BA=0.2639
[22/54] corral.tsv.gz: BA=0.7333
[23/54] dermatology.tsv.gz: BA=0.9053
[24/54] dis.tsv.gz: BA=0.4997
[25/54] dna.tsv.gz: BA=0.9408
[26/54] hypothyroid.tsv.gz: BA=0.5028
[27/54] irish.tsv.gz: BA=0.8015
[28/54] kr_vs_kp.tsv.gz: BA=0.9825
[29/54] labor.tsv.gz: BA=0.6277
[30/54] mfeat_factors.tsv.gz: BA=0.9635
[31/54] mfeat_karhunen.tsv.gz: BA=0.9455
[32/54] mfeat_pixel.tsv.gz: BA=0.9635
[33/54] mofn_3_7_10.tsv.gz: BA=0.9743
[34/54] monk3.tsv.gz: BA=0.7988
[35/54] mushroom.tsv.gz: BA=0.9978
[36/54] mux6.tsv.gz: BA=0.6016
[37/54] new_thyroid.tsv.gz: BA=0.8832
[38/54] optdigits.tsv.gz: BA=0.9740
[39/54] page_blocks.tsv.gz: BA=0.7029
[40/54] pendigits.tsv.gz: BA=0.9904
[41/54] penguins.tsv.gz: BA=0.7722
[42/54] prnn_crabs.tsv.gz: BA=0.5950
[43/54] prnn_synth.tsv.gz: BA=0.7640
[44/54] segmentation.tsv.gz: BA=0.9074
[45/54] shuttle.tsv.gz: BA=0.8367
[46/54] soybean.tsv.gz: BA=0.8583
[47/54] spambase.tsv.gz: BA=0.9322
[48/54] spectf.tsv.gz: BA=0.6679
[49/54] texture.tsv.gz: BA=0.9893
[50/54] threeOf9.tsv.gz: BA=0.7748
[51/54] tokyo1.tsv.gz: BA=0.9059
[52/54] twonorm.tsv.gz: BA=0.9753
[53/54] wine_recognition.tsv.gz: BA=0.8804
[54/54] xd6.tsv.gz: BA=0.6609

Top Results (54 datasets):

                           dataset  accuracy  macro_f1  balanced_accuracy
0          agaricus_lepiota.tsv.gz  0.998527  0.998524           0.998496
1                     allbp.tsv.gz  0.963680  0.454407           0.417236
2                  allhyper.tsv.gz  0.972686  0.246539           0.249864
3                   allhypo.tsv.gz  0.932361  0.463106           0.417266
4                    allrep.tsv.gz  0.967126  0.245822           0.250000
5    analcatdata_authorship.tsv.gz  0.985731  0.984568           0.985131
6    analcatdata_bankruptcy.tsv.gz  0.620000  0.600673           0.620000
7   analcatdata_creditscore.tsv.gz  0.650000  0.393939           0.445205
8   analcatdata_cyyoung9302.tsv.gz  0.717391  0.452381           0.471521
9       analcatdata_lawsuit.tsv.gz  0.882576  0.525703           0.524060
10              ann_thyroid.tsv.gz  0.982500  0.902972           0.877983
11             appendicitis.tsv.gz  0.801887  0.682499           0.679272
12                 backache.tsv.gz  0.811111  0.447853           0.470968
13            breast_cancer.tsv.gz  0.706294  0.602778           0.597542
14                    chess.tsv.gz  0.980601  0.980572           0.980813
15                    churn.tsv.gz  0.910600  0.779228           0.735861
16                   clean1.tsv.gz  0.794118  0.790564           0.790564
17                   clean2.tsv.gz  0.996817  0.993880           0.992490
18                 coil2000.tsv.gz  0.939829  0.486175           0.500528
19                  collins.tsv.gz  0.484536  0.388832           0.398269
20               confidence.tsv.gz  0.263889  0.230341           0.263889
21                   corral.tsv.gz  0.725000  0.724828           0.733333
22              dermatology.tsv.gz  0.923497  0.915841           0.905327
23                      dis.tsv.gz  0.984093  0.495991           0.499731
24                      dna.tsv.gz  0.945700  0.939569           0.940833
25              hypothyroid.tsv.gz  0.951628  0.494055           0.502813
26                    irish.tsv.gz  0.804000  0.801510           0.801510
27                 kr_vs_kp.tsv.gz  0.982478  0.982446           0.982527
28                    labor.tsv.gz  0.561404  0.560863           0.627703
29            mfeat_factors.tsv.gz  0.963500  0.963491           0.963500
30           mfeat_karhunen.tsv.gz  0.945500  0.945439           0.945500
31              mfeat_pixel.tsv.gz  0.963500  0.963516           0.963500
32              mofn_3_7_10.tsv.gz  0.988671  0.983211           0.974315
33                    monk3.tsv.gz  0.799639  0.799088           0.798820
34                 mushroom.tsv.gz  0.997784  0.997782           0.997808
35                     mux6.tsv.gz  0.601562  0.600367           0.601562
36              new_thyroid.tsv.gz  0.916279  0.874836           0.883175
37                optdigits.tsv.gz  0.974021  0.974016           0.974025
38              page_blocks.tsv.gz  0.965101  0.776825           0.702943
39                pendigits.tsv.gz  0.990357  0.990372           0.990384
40                 penguins.tsv.gz  0.858859  0.781746           0.772227
41               prnn_crabs.tsv.gz  0.595000  0.577233           0.595000
42               prnn_synth.tsv.gz  0.764000  0.760315           0.764000
43             segmentation.tsv.gz  0.907359  0.906209           0.907359
44                  shuttle.tsv.gz  0.998466  0.829200           0.836691
45                  soybean.tsv.gz  0.844444  0.871799           0.858325
46                 spambase.tsv.gz  0.936753  0.933564           0.932188
47                   spectf.tsv.gz  0.770774  0.681191           0.667903
48                  texture.tsv.gz  0.989273  0.989271           0.989273
49                 threeOf9.tsv.gz  0.779297  0.776119           0.774750
50                   tokyo1.tsv.gz  0.910323  0.903385           0.905935
51                  twonorm.tsv.gz  0.975270  0.975270           0.975270
52         wine_recognition.tsv.gz  0.876404  0.875247           0.880416
53                      xd6.tsv.gz  0.763618  0.672611           0.660906

In [20]:
# Rank and save top results
rank_metric = "accuracy"

top_ranked_df = top_results_df.sort_values(by=rank_metric, ascending=False).reset_index(drop=True)
top_ranked_df.insert(0, "rank", top_ranked_df.index + 1)

display(top_ranked_df)
top_ranked_df.to_csv("top_mlp_results_ranked.csv", index=False)
print("Top ranked results saved to: top_mlp_results_ranked.csv")

,rank,dataset,accuracy,macro_f1,balanced_accuracy
0,1,agaricus_lepiota.tsv.gz,0.998527,0.998524,0.998496
1,2,shuttle.tsv.gz,0.998466,0.829200,0.836691
2,3,mushroom.tsv.gz,0.997784,0.997782,0.997808
3,4,clean2.tsv.gz,0.996817,0.993880,0.992490
4,5,pendigits.tsv.gz,0.990357,0.990372,0.990384
5,6,texture.tsv.gz,0.989273,0.989271,0.989273
6,7,mofn_3_7_10.tsv.gz,0.988671,0.983211,0.974315
7,8,analcatdata_authorship.tsv.gz,0.985731,0.984568,0.985131
8,9,dis.tsv.gz,0.984093,0.495991,0.499731
9,10,ann_thyroid.tsv.gz,0.982500,0.902972,0.877983
10,11,kr_vs_kp.tsv.gz,0.982478,0.982446,0.982527
11,12,chess.tsv.gz,0.980601,0.980572,0.980813
12,13,twonorm.tsv.gz,0.975270,0.975270,0.975270
13,14,optdigits.tsv.gz,0.974021,0.974016,0.974025
14,15,allhyper.tsv.gz,0.972686,0.246539,0.249864
15,16,allrep.tsv.gz,0.967126,0.245822,0.250000
16,17,page_blocks.tsv.gz,0.965101,0.776825,0.702943
17,18,allbp.tsv.gz,0.963680,0.454407,0.417236
18,19,mfeat_pixel.tsv.gz,0.963500,0.963516,0.963500
19,20,mfeat_factors.tsv.gz,0.963500,0.963491,0.963500
20,21,hypothyroid.tsv.gz,0.951628,0.494055,0.502813
21,22,dna.tsv.gz,0.945700,0.939569,0.940833
22,23,mfeat_karhunen.tsv.gz,0.945500,0.945439,0.945500
23,24,coil2000.tsv.gz,0.939829,0.486175,0.500528
24,25,spambase.tsv.gz,0.936753,0.933564,0.932188
25,26,allhypo.tsv.gz,0.932361,0.463106,0.417266
26,27,dermatology.tsv.gz,0.923497,0.915841,0.905327
27,28,new_thyroid.tsv.gz,0.916279,0.874836,0.883175
28,29,churn.tsv.gz,0.910600,0.779228,0.735861
29,30,tokyo1.tsv.gz,0.910323,0.903385,0.905935
30,31,segmentation.tsv.gz,0.907359,0.906209,0.907359
31,32,analcatdata_lawsuit.tsv.gz,0.882576,0.525703,0.524060
32,33,wine_recognition.tsv.gz,0.876404,0.875247,0.880416
33,34,penguins.tsv.gz,0.858859,0.781746,0.772227
34,35,soybean.tsv.gz,0.844444,0.871799,0.858325
35,36,backache.tsv.gz,0.811111,0.447853,0.470968
36,37,irish.tsv.gz,0.804000,0.801510,0.801510
37,38,appendicitis.tsv.gz,0.801887,0.682499,0.679272
38,39,monk3.tsv.gz,0.799639,0.799088,0.798820
39,40,clean1.tsv.gz,0.794118,0.790564,0.790564
40,41,threeOf9.tsv.gz,0.779297,0.776119,0.774750
41,42,spectf.tsv.gz,0.770774,0.681191,0.667903
42,43,prnn_synth.tsv.gz,0.764000,0.760315,0.764000
43,44,xd6.tsv.gz,0.763618,0.672611,0.660906
44,45,corral.tsv.gz,0.725000,0.724828,0.733333
45,46,analcatdata_cyyoung9302.tsv.gz,0.717391,0.452381,0.471521
46,47,breast_cancer.tsv.gz,0.706294,0.602778,0.597542
47,48,analcatdata_creditscore.tsv.gz,0.650000,0.393939,0.445205
48,49,analcatdata_bankruptcy.tsv.gz,0.620000,0.600673,0.620000
49,50,mux6.tsv.gz,0.601562,0.600367,0.601562
50,51,prnn_crabs.tsv.gz,0.595000,0.577233,0.595000
51,52,labor.tsv.gz,0.561404,0.560863,0.627703
52,53,collins.tsv.gz,0.484536,0.388832,0.398269
53,54,confidence.tsv.gz,0.263889,0.230341,0.263889

Top ranked results saved to: top_mlp_results_ranked.csv

## Bottom File: Load CSV, then Train on ALL Listed Datasets

In [14]:
bottom_df = pd.read_csv(BOTTOM_FILE)

print("Bottom CSV length:", len(bottom_df))
display(bottom_df.head(10))

print("\nLoading and preparing all bottom datasets...")

Bottom CSV length: 49

,dataset,target_column,rows,features,classes,class_imbalance,missing_values_count,missing_values_ratio,numeric_features,categorical_features,feature_type
0,GAMETES_Epistasis_2_Way_1000atts_0.4H_EDM_1_ED...,target,1600,1000,2,0.000000,0,0,1000,0,numeric
1,GAMETES_Epistasis_2_Way_20atts_0.1H_EDM_1_1.ts...,target,1600,20,2,0.000000,0,0,20,0,numeric
2,GAMETES_Epistasis_2_Way_20atts_0.4H_EDM_1_1.ts...,target,1600,20,2,0.000000,0,0,20,0,numeric
3,GAMETES_Epistasis_3_Way_20atts_0.2H_EDM_1_1.ts...,target,1600,20,2,0.000000,0,0,20,0,numeric
4,GAMETES_Heterogeneity_20atts_1600_Het_0.4_0.2_...,target,1600,20,2,0.000000,0,0,20,0,numeric
5,GAMETES_Heterogeneity_20atts_1600_Het_0.4_0.2_...,target,1600,20,2,0.000000,0,0,20,0,numeric
6,Hill_Valley_with_noise.tsv.gz,target,1212,100,2,0.000000,0,0,100,0,numeric
7,Hill_Valley_without_noise.tsv.gz,target,1212,100,2,0.000049,0,0,100,0,numeric
8,analcatdata_aids.tsv.gz,target,50,4,2,0.000000,0,0,4,0,numeric
9,analcatdata_asbestos.tsv.gz,target,83,3,2,0.005879,0,0,3,0,numeric

Loading and preparing all bottom datasets...

## Bottom Dataset: Explicit MLP Code

In [15]:
# MLP training loop for all bottom datasets
bottom_results = []

for idx, row in bottom_df.iterrows():
    dataset_name = row["dataset"]
    dataset_path = f"../data/{dataset_name}"
    
    try:
        # Load dataset
        data = pd.read_csv(dataset_path, compression="gzip", sep="\t")
        label_col = "class" if "class" in data.columns else "target"
        
        X = data.drop(columns=[label_col]).values.astype(float)
        y = data[label_col].values
        
        # MLP training
        mlp = MLPClassifier(
            hidden_layer_sizes=(100,),
            activation="relu",
            solver="adam",
            max_iter=1000,
            early_stopping=True,
            random_state=324089
        )
        
        pipeline = make_pipeline(RobustScaler(), mlp)
        cv = StratifiedKFold(n_splits=10, shuffle=True, random_state=90483257)
        pred = cross_val_predict(pipeline, X, y, cv=cv)
        
        # Metrics
        accuracy = accuracy_score(y, pred)
        macro_f1 = f1_score(y, pred, average="macro", zero_division=0)
        balanced_accuracy = balanced_accuracy_score(y, pred)
        
        bottom_results.append({
            "dataset": dataset_name,
            "accuracy": accuracy,
            "macro_f1": macro_f1,
            "balanced_accuracy": balanced_accuracy,
        })
        
        print(f"[{idx+1}/{len(bottom_df)}] {dataset_name}: BA={balanced_accuracy:.4f}")
    except Exception as e:
        print(f"[{idx+1}/{len(bottom_df)}] {dataset_name}: ERROR - {e}")

bottom_results_df = pd.DataFrame(bottom_results)
print(f"\nBottom Results ({len(bottom_results_df)} datasets):")
display(bottom_results_df)

[1/49] GAMETES_Epistasis_2_Way_1000atts_0.4H_EDM_1_EDM_1_1.tsv.gz: BA=0.4831
[2/49] GAMETES_Epistasis_2_Way_20atts_0.1H_EDM_1_1.tsv.gz: BA=0.4962
[3/49] GAMETES_Epistasis_2_Way_20atts_0.4H_EDM_1_1.tsv.gz: BA=0.5931
[4/49] GAMETES_Epistasis_3_Way_20atts_0.2H_EDM_1_1.tsv.gz: BA=0.5225
[5/49] GAMETES_Heterogeneity_20atts_1600_Het_0.4_0.2_50_EDM_2_001.tsv.gz: BA=0.5444
[6/49] GAMETES_Heterogeneity_20atts_1600_Het_0.4_0.2_75_EDM_2_001.tsv.gz: BA=0.6044
[7/49] Hill_Valley_with_noise.tsv.gz: BA=0.5231
[8/49] Hill_Valley_without_noise.tsv.gz: BA=0.4826
[9/49] analcatdata_aids.tsv.gz: BA=0.4400
[10/49] analcatdata_asbestos.tsv.gz: BA=0.7512
[11/49] analcatdata_boxing1.tsv.gz: BA=0.5211
[12/49] analcatdata_boxing2.tsv.gz: BA=0.5813
[13/49] analcatdata_dmft.tsv.gz: BA=0.1892
[14/49] analcatdata_germangss.tsv.gz: BA=0.3350
[15/49] analcatdata_happiness.tsv.gz: BA=0.3333
[16/49] bupa.tsv.gz: BA=0.6195
[17/49] calendarDOW.tsv.gz: BA=0.4521
[18/49] cloud.tsv.gz: BA=0.3289
[19/49] connect_4.tsv.gz: BA=0.5940
[20/49] flags.tsv.gz: BA=0.2428
[21/49] haberman.tsv.gz: BA=0.5012
[22/49] hayes_roth.tsv.gz: BA=0.3378
[23/49] iris.tsv.gz: BA=0.7733
[24/49] krkopt.tsv.gz: BA=0.4550
[25/49] led24.tsv.gz: BA=0.7224
[26/49] led7.tsv.gz: BA=0.7335
[27/49] letter.tsv.gz: BA=0.9448
[28/49] mfeat_morphological.tsv.gz: BA=0.6920
[29/49] monk1.tsv.gz: BA=0.5288
[30/49] monk2.tsv.gz: BA=0.4966
[31/49] mux6.tsv.gz: BA=0.6016
[32/49] new_thyroid.tsv.gz: BA=0.8832
[33/49] page_blocks.tsv.gz: BA=0.7029
[34/49] parity5+5.tsv.gz: BA=0.4818
[35/49] parity5.tsv.gz: BA=0.5625
[36/49] pendigits.tsv.gz: BA=0.9904

c:\Users\EYONGEBOB\Desktop\PMLB Project\.venv\lib\site-packages\sklearn\model_selection\_split.py:811: UserWarning: The least populated class in y has only 8 members, which is less than n_splits=10.
  warnings.warn(

[37/49] poker.tsv.gz: BA=0.6348
[38/49] postoperative_patient_data.tsv.gz: BA=0.4844
[39/49] profb.tsv.gz: BA=0.5022
[40/49] saheart.tsv.gz: BA=0.6374
[41/49] schizo.tsv.gz: BA=0.3267
[42/49] segmentation.tsv.gz: BA=0.9074
[43/49] sonar.tsv.gz: BA=0.7624
[44/49] tae.tsv.gz: BA=0.3675
[45/49] tic_tac_toe.tsv.gz: BA=0.5306
[46/49] vowel.tsv.gz: BA=0.4444
[47/49] wine_quality_red.tsv.gz: BA=0.2576

c:\Users\EYONGEBOB\Desktop\PMLB Project\.venv\lib\site-packages\sklearn\model_selection\_split.py:811: UserWarning: The least populated class in y has only 5 members, which is less than n_splits=10.
  warnings.warn(

[48/49] wine_quality_white.tsv.gz: BA=0.2416
[49/49] yeast.tsv.gz: BA=0.3951

Bottom Results (49 datasets):

,dataset,accuracy,macro_f1,balanced_accuracy
0,GAMETES_Epistasis_2_Way_1000atts_0.4H_EDM_1_ED...,0.483125,0.483036,0.483125
1,GAMETES_Epistasis_2_Way_20atts_0.1H_EDM_1_1.ts...,0.496250,0.495443,0.496250
2,GAMETES_Epistasis_2_Way_20atts_0.4H_EDM_1_1.ts...,0.593125,0.593112,0.593125
3,GAMETES_Epistasis_3_Way_20atts_0.2H_EDM_1_1.ts...,0.522500,0.522070,0.522500
4,GAMETES_Heterogeneity_20atts_1600_Het_0.4_0.2_...,0.544375,0.543146,0.544375
5,GAMETES_Heterogeneity_20atts_1600_Het_0.4_0.2_...,0.604375,0.604004,0.604375
6,Hill_Valley_with_noise.tsv.gz,0.523102,0.502262,0.523102
7,Hill_Valley_without_noise.tsv.gz,0.482673,0.482546,0.482565
8,analcatdata_aids.tsv.gz,0.440000,0.356618,0.440000
9,analcatdata_asbestos.tsv.gz,0.771084,0.753786,0.751175
10,analcatdata_boxing1.tsv.gz,0.591667,0.517677,0.521062
11,analcatdata_boxing2.tsv.gz,0.568182,0.560899,0.581275
12,analcatdata_dmft.tsv.gz,0.190715,0.163502,0.189163
13,analcatdata_germangss.tsv.gz,0.335000,0.324094,0.335000
14,analcatdata_happiness.tsv.gz,0.333333,0.229167,0.333333
15,bupa.tsv.gz,0.620290,0.619253,0.619486
16,calendarDOW.tsv.gz,0.476190,0.456951,0.452143
17,cloud.tsv.gz,0.305556,0.264455,0.328869
18,connect_4.tsv.gz,0.805971,0.597680,0.593993
19,flags.tsv.gz,0.308989,0.216909,0.242778
20,haberman.tsv.gz,0.725490,0.442575,0.501235
21,hayes_roth.tsv.gz,0.362500,0.319891,0.337769
22,iris.tsv.gz,0.773333,0.762548,0.773333
23,krkopt.tsv.gz,0.529085,0.466536,0.454985
24,led24.tsv.gz,0.722812,0.718919,0.722358
25,led7.tsv.gz,0.737812,0.728729,0.733539
26,letter.tsv.gz,0.945100,0.944885,0.944827
27,mfeat_morphological.tsv.gz,0.692000,0.687879,0.692000
28,monk1.tsv.gz,0.528777,0.527744,0.528777
29,monk2.tsv.gz,0.640599,0.423143,0.496633
30,mux6.tsv.gz,0.601562,0.600367,0.601562
31,new_thyroid.tsv.gz,0.916279,0.874836,0.883175
32,page_blocks.tsv.gz,0.965101,0.776825,0.702943
33,parity5+5.tsv.gz,0.482206,0.481180,0.481849
34,parity5.tsv.gz,0.562500,0.562500,0.562500
35,pendigits.tsv.gz,0.990357,0.990372,0.990384
36,poker.tsv.gz,0.995366,0.680158,0.634753
37,postoperative_patient_data.tsv.gz,0.704545,0.413333,0.484375
38,profb.tsv.gz,0.654762,0.433455,0.502232
39,saheart.tsv.gz,0.696970,0.642739,0.637438
40,schizo.tsv.gz,0.558824,0.266963,0.326693
41,segmentation.tsv.gz,0.907359,0.906209,0.907359
42,sonar.tsv.gz,0.764423,0.762839,0.762376
43,tae.tsv.gz,0.370861,0.344679,0.367483
44,tic_tac_toe.tsv.gz,0.663883,0.477673,0.530621
45,vowel.tsv.gz,0.444444,0.420209,0.444444
46,wine_quality_red.tsv.gz,0.572858,0.260024,0.257619
47,wine_quality_white.tsv.gz,0.560637,0.246326,0.241645
48,yeast.tsv.gz,0.572684,0.408818,0.395132

In [21]:
# Rank and save bottom results
rank_metric = "accuracy"

bottom_ranked_df = bottom_results_df.sort_values(by=rank_metric, ascending=False).reset_index(drop=True)
bottom_ranked_df.insert(0, "rank", bottom_ranked_df.index + 1)

display(bottom_ranked_df)
bottom_ranked_df.to_csv("bottom_mlp_results_ranked.csv", index=False)
print("Bottom ranked results saved to: bottom_mlp_results_ranked.csv")

,rank,dataset,accuracy,macro_f1,balanced_accuracy
0,1,poker.tsv.gz,0.995366,0.680158,0.634753
1,2,pendigits.tsv.gz,0.990357,0.990372,0.990384
2,3,page_blocks.tsv.gz,0.965101,0.776825,0.702943
3,4,letter.tsv.gz,0.945100,0.944885,0.944827
4,5,new_thyroid.tsv.gz,0.916279,0.874836,0.883175
5,6,segmentation.tsv.gz,0.907359,0.906209,0.907359
6,7,connect_4.tsv.gz,0.805971,0.597680,0.593993
7,8,iris.tsv.gz,0.773333,0.762548,0.773333
8,9,analcatdata_asbestos.tsv.gz,0.771084,0.753786,0.751175
9,10,sonar.tsv.gz,0.764423,0.762839,0.762376
10,11,led7.tsv.gz,0.737812,0.728729,0.733539
11,12,haberman.tsv.gz,0.725490,0.442575,0.501235
12,13,led24.tsv.gz,0.722812,0.718919,0.722358
13,14,postoperative_patient_data.tsv.gz,0.704545,0.413333,0.484375
14,15,saheart.tsv.gz,0.696970,0.642739,0.637438
15,16,mfeat_morphological.tsv.gz,0.692000,0.687879,0.692000
16,17,tic_tac_toe.tsv.gz,0.663883,0.477673,0.530621
17,18,profb.tsv.gz,0.654762,0.433455,0.502232
18,19,monk2.tsv.gz,0.640599,0.423143,0.496633
19,20,bupa.tsv.gz,0.620290,0.619253,0.619486
20,21,GAMETES_Heterogeneity_20atts_1600_Het_0.4_0.2_...,0.604375,0.604004,0.604375
21,22,mux6.tsv.gz,0.601562,0.600367,0.601562
22,23,GAMETES_Epistasis_2_Way_20atts_0.4H_EDM_1_1.ts...,0.593125,0.593112,0.593125
23,24,analcatdata_boxing1.tsv.gz,0.591667,0.517677,0.521062
24,25,wine_quality_red.tsv.gz,0.572858,0.260024,0.257619
25,26,yeast.tsv.gz,0.572684,0.408818,0.395132
26,27,analcatdata_boxing2.tsv.gz,0.568182,0.560899,0.581275
27,28,parity5.tsv.gz,0.562500,0.562500,0.562500
28,29,wine_quality_white.tsv.gz,0.560637,0.246326,0.241645
29,30,schizo.tsv.gz,0.558824,0.266963,0.326693
30,31,GAMETES_Heterogeneity_20atts_1600_Het_0.4_0.2_...,0.544375,0.543146,0.544375
31,32,krkopt.tsv.gz,0.529085,0.466536,0.454985
32,33,monk1.tsv.gz,0.528777,0.527744,0.528777
33,34,Hill_Valley_with_noise.tsv.gz,0.523102,0.502262,0.523102
34,35,GAMETES_Epistasis_3_Way_20atts_0.2H_EDM_1_1.ts...,0.522500,0.522070,0.522500
35,36,GAMETES_Epistasis_2_Way_20atts_0.1H_EDM_1_1.ts...,0.496250,0.495443,0.496250
36,37,GAMETES_Epistasis_2_Way_1000atts_0.4H_EDM_1_ED...,0.483125,0.483036,0.483125
37,38,Hill_Valley_without_noise.tsv.gz,0.482673,0.482546,0.482565
38,39,parity5+5.tsv.gz,0.482206,0.481180,0.481849
39,40,calendarDOW.tsv.gz,0.476190,0.456951,0.452143
40,41,vowel.tsv.gz,0.444444,0.420209,0.444444
41,42,analcatdata_aids.tsv.gz,0.440000,0.356618,0.440000
42,43,tae.tsv.gz,0.370861,0.344679,0.367483
43,44,hayes_roth.tsv.gz,0.362500,0.319891,0.337769
44,45,analcatdata_germangss.tsv.gz,0.335000,0.324094,0.335000
45,46,analcatdata_happiness.tsv.gz,0.333333,0.229167,0.333333
46,47,flags.tsv.gz,0.308989,0.216909,0.242778
47,48,cloud.tsv.gz,0.305556,0.264455,0.328869
48,49,analcatdata_dmft.tsv.gz,0.190715,0.163502,0.189163

Bottom ranked results saved to: bottom_mlp_results_ranked.csv